sudo: false
language: node_js
node_js:
 - node
cache: npm
branches:
  only:
  - master
before_script:
  - npm install yaspeller -g
script:
  - find ./async-book-ru -iname '*.md' | xargs yaspeller -c common-configs/.yaspellerrc
