[book]
title = "Asynchronous Programming in Rust"
authors = ["Taylor Cramer"]

[build]
create-missing = true

[preprocess.links]

[output.html]
google-analytics="UA-142155799-7"

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
